server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vb67yyhxo2sps7v5zo.mysql.zhangbei.rds.aliyuncs.com/project?serverTimezone=UTC
    username: project
    password: BLOODline794613
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
